"""engine.py — ReviewEngine: orchestrates diff → LLM → ReviewResult.

Architecture (adapted from cortex-agent/src/agent/engine.py):
  - Loads the review prompt from review.xml
  - Injects the diff into the user message
  - Calls LLMClient (async, with failover)
  - Parses the LLM output into a ReviewResult
  - Supports streaming output for real-time terminal display
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import AsyncGenerator

from src.config.settings import Settings
from src.reviewer.diff import DiffResult
from src.reviewer.llm import LLMClient
from src.reviewer.report import ReviewResult

logger = logging.getLogger(__name__)

_PROMPTS_DIR = Path(__file__).parent / "prompts"


def _load_prompt(name: str) -> str:
    """Load an XML prompt file and strip the outer <system_prompt> tags."""
    path = _PROMPTS_DIR / f"{name}.xml"
    if not path.exists():
        raise FileNotFoundError(f"Prompt not found: {path}")
    text = path.read_text(encoding="utf-8")
    # Strip the wrapping <system_prompt>...</system_prompt> tags
    text = text.strip()
    if text.startswith("<system_prompt>"):
        text = text[len("<system_prompt>"):].strip()
    if text.endswith("</system_prompt>"):
        text = text[: -len("</system_prompt>")].strip()
    return text


def _build_user_message(diff: DiffResult) -> str:
    """Build the user message that describes the diff to the LLM."""
    lines = []

    if diff.title:
        lines.append(f"**Title:** {diff.title}")
    if diff.author:
        lines.append(f"**Author:** {diff.author}")
    if diff.base_ref or diff.head_ref:
        lines.append(f"**Diff:** `{diff.base_ref}...{diff.head_ref}`")
    if diff.url:
        lines.append(f"**URL:** {diff.url}")
    if diff.description:
        lines.append(f"\n**Description:**\n{diff.description.strip()}")

    lines.append(f"\n**Stats:** {diff.stats}")
    if diff.changed_files:
        files_list = "\n".join(f"  - {f}" for f in diff.changed_files[:30])
        if len(diff.changed_files) > 30:
            files_list += f"\n  ... and {len(diff.changed_files) - 30} more"
        lines.append(f"\n**Changed files:**\n{files_list}")

    lines.append(f"\n---\n\n```diff\n{diff.raw_diff}\n```")
    return "\n".join(lines)


class ReviewEngine:
    """Orchestrates the full code review pipeline."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._llm = LLMClient.from_settings(settings.llm)
        self._system_prompt = _load_prompt("review")

    # ── Public: full review (returns complete ReviewResult) ──────────────────

    async def review(self, diff: DiffResult) -> ReviewResult:
        """
        Run a full review of the given diff.
        Returns a ReviewResult with the complete markdown report.
        """
        diff = diff.truncate(self._settings.max_diff_lines)

        user_message = _build_user_message(diff)
        messages = [
            {"role": "system", "content": self._system_prompt},
            {"role": "user",   "content": user_message},
        ]

        logger.info(
            "review.started source=%s title=%s files=%d",
            diff.source, diff.title[:60], len(diff.changed_files),
        )

        response = await self._llm.chat(messages)

        if response.text.startswith("Error:"):
            raise RuntimeError(f"LLM call failed: {response.text}")

        logger.info(
            "review.completed tokens=%d/%d",
            response.input_tokens, response.output_tokens,
        )

        return ReviewResult.from_llm_output(
            raw=response.text,
            source=diff.source,
            title=diff.title,
            url=diff.url,
            author=diff.author,
            base_ref=diff.base_ref,
            head_ref=diff.head_ref,
            changed_files=diff.changed_files,
            model=response.model or self._settings.llm.model,
            input_tokens=response.input_tokens,
            output_tokens=response.output_tokens,
        )

    # ── Public: streaming review (yields text chunks for live display) ────────

    async def review_stream(self, diff: DiffResult) -> AsyncGenerator[str, None]:
        """
        Stream the review as it is generated by the LLM.
        Yields raw text chunks for real-time terminal or SSE output.
        The caller is responsible for assembling the complete text if needed.
        """
        diff = diff.truncate(self._settings.max_diff_lines)
        user_message = _build_user_message(diff)
        messages = [
            {"role": "system", "content": self._system_prompt},
            {"role": "user",   "content": user_message},
        ]

        logger.info(
            "review.stream.started source=%s title=%s",
            diff.source, diff.title[:60],
        )

        async for chunk in self._llm.stream(messages):
            yield chunk
